## Copyright 2018 Jason Vander Woude
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.


##               __          ____        ____  _____
##              / /         / __ \      / __ \/_  _/
##             / /   ____  / /_/ /_  __/ /_/ / / / __   __________  __
##            / /   / _  \/ _  _/\ \/ / _  _/ / / /  | / /_  __/ /_/ /
##           / /___/ /_/ / /_\ \  \  / / \ \_/ /_/ /||/ / / / / __  /
##          /_____/_/ /_/______/  /_/_/  /_/____/_/ |__/ /_/ /_/ /_/
##
##                  L O W - C O V E R A G E   B I A L L E L I C
##                    R - P A C K A G E   I M P U T A T I O N
##


################################################################################
##                                                                            ##
##            ATTENTION! THIS FILE IS AUTO-GENERATED. DO NOT EDIT             ##
##                                                                            ##
################################################################################
##                                                                            ##
## This file is auto-generated by multi-model-symbolics.sage for populations  ##
## bred under the following breeding scheme:                                  ##
##                                                                            ##
## F1BC1                                                                      ##
##                                                                            ##
## To generate a similar file for other types of breeding schemes, edit the   ##
## multi-model-symbolics.sage file according to the comments in that          ##
## file. Then load multi-model-symbolics.sage in a SAGE interpreter and run   ##
## the function `parse_probs_to_R`. The first parameter should be the string  ##
## that you use to define your breeding scheme. The second parameter should   ##
## be the name of the directory where the result should be temporarily saved. ##
## The resulting file must then be moved into the following directory in the  ##
## labyrinth package (inst/extdata/transitions-probs/).                       ##
##                                                                            ##
## To download SAGE, visit https://www.sagemath.org/download.html             ##
##                                                                            ##
## There is a seperate file for each model because when LaByRInth runs, only  ##
## one model will be needed, so there is no need to source the code for all   ##
## other models.                                                              ##
##                                                                            ##
################################################################################

site.pair.transition.probs <- list(
    list(
        function(r) {
            matrix(c(
                1, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/2, 1/4, 1/4, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/2, 1/4, 1/4, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/2, 1/2, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/2, 1/4, 1/4, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4, 1/4, 1/4, 1/4,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4, 1/4, 1/4, 1/4,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4, 1/4, 1/2,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/2, 1/4, 1/4, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4, 1/4, 1/4, 1/4,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4, 1/4, 1/4, 1/4,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4, 1/4, 1/2,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/2, 1/2, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4, 1/4, 1/2,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4, 1/4, 1/2,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 1,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                1/2, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/2*r + 1/2, 1/4*r, 1/4*r, 0,
                1/4*r, -1/4*r + 1/4, 0, 0,
                1/4*r, 0, -1/4*r + 1/4, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/2*r, -1/4*r + 1/4, -1/4*r + 1/4, 0,
                -1/4*r + 1/4, 1/4*r, 0, 0,
                -1/4*r + 1/4, 0, 1/4*r, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4, 1/4, 0,
                0, 1/4, 0, 0,
                0, 0, 1/4, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4, 1/8, 1/8, 0,
                1/8, 0, 1/8, 0,
                1/8, 1/8, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, 1/8, 1/8, -1/4*r + 1/4,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 1/4,
                0, 1/8, 0, 1/8,
                0, 0, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4, 1/8, 1/8, 0,
                1/8, 0, 1/8, 0,
                1/8, 1/8, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, 1/8, 1/8, -1/4*r + 1/4,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 1/4,
                0, 1/8, 0, 1/8,
                0, 0, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4, 1/4, 0,
                0, 0, 1/4, 0,
                0, 1/4, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, -1/4*r + 1/4, -1/4*r + 1/4, 1/2*r,
                0, 0, 1/4*r, -1/4*r + 1/4,
                0, 1/4*r, 0, -1/4*r + 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4*r, 1/4*r, -1/2*r + 1/2,
                0, 0, -1/4*r + 1/4, 1/4*r,
                0, -1/4*r + 1/4, 0, 1/4*r,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 1/2,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                1/2, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/2*r, -1/4*r + 1/4, -1/4*r + 1/4, 0,
                -1/4*r + 1/4, 1/4*r, 0, 0,
                -1/4*r + 1/4, 0, 1/4*r, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/2*r + 1/2, 1/4*r, 1/4*r, 0,
                1/4*r, -1/4*r + 1/4, 0, 0,
                1/4*r, 0, -1/4*r + 1/4, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4, 1/4, 0,
                0, 1/4, 0, 0,
                0, 0, 1/4, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4, 1/8, 1/8, 0,
                1/8, 0, 1/8, 0,
                1/8, 1/8, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, 1/8, 1/8, -1/4*r + 1/4,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 1/4,
                0, 1/8, 0, 1/8,
                0, 0, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4, 1/8, 1/8, 0,
                1/8, 0, 1/8, 0,
                1/8, 1/8, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, 1/8, 1/8, -1/4*r + 1/4,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 1/4,
                0, 1/8, 0, 1/8,
                0, 0, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4, 1/4, 0,
                0, 0, 1/4, 0,
                0, 1/4, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4*r, 1/4*r, -1/2*r + 1/2,
                0, 0, -1/4*r + 1/4, 1/4*r,
                0, -1/4*r + 1/4, 0, 1/4*r,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, -1/4*r + 1/4, -1/4*r + 1/4, 1/2*r,
                0, 0, 1/4*r, -1/4*r + 1/4,
                0, 1/4*r, 0, -1/4*r + 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 1/2,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/2, 0, 0, 0,
                1/2, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4, 1/4, 0, 0,
                1/4, 0, 1/4, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4, 1/4, 0, 0,
                1/4, 0, 1/4, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/2, 0, 0,
                0, 0, 1/2, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4, 0, 1/4, 0,
                1/4, 1/4, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 1/8, 1/8,
                1/8, 1/8, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 1/8, 1/8,
                1/8, 1/8, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/4, 0, 1/4,
                0, 0, 1/4, 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4, 0, 1/4, 0,
                1/4, 1/4, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 1/8, 1/8,
                1/8, 1/8, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 1/8, 1/8,
                1/8, 1/8, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/4, 0, 1/4,
                0, 0, 1/4, 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/2, 0,
                0, 1/2, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/4, 1/4,
                0, 1/4, 0, 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/4, 1/4,
                0, 1/4, 0, 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 1/2,
                0, 0, 0, 1/2,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                1/2, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4, 1/8, 1/8, 0,
                1/8, 0, 1/8, 0,
                1/8, 1/8, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4, 1/8, 1/8, 0,
                1/8, 0, 1/8, 0,
                1/8, 1/8, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4, 1/4, 0,
                0, 0, 1/4, 0,
                0, 1/4, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/2*r + 1/2, 1/4*r, 1/4*r, 0,
                1/4*r, -1/4*r + 1/4, 0, 0,
                1/4*r, 0, -1/4*r + 1/4, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, -1/4*r + 1/4, -1/4*r + 1/4, 1/2*r,
                0, 0, 1/4*r, -1/4*r + 1/4,
                0, 1/4*r, 0, -1/4*r + 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/2*r, -1/4*r + 1/4, -1/4*r + 1/4, 0,
                -1/4*r + 1/4, 1/4*r, 0, 0,
                -1/4*r + 1/4, 0, 1/4*r, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, 1/8, 1/8, -1/4*r + 1/4,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, 1/8, 1/8, -1/4*r + 1/4,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4*r, 1/4*r, -1/2*r + 1/2,
                0, 0, -1/4*r + 1/4, 1/4*r,
                0, -1/4*r + 1/4, 0, 1/4*r,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4, 1/4, 0,
                0, 1/4, 0, 0,
                0, 0, 1/4, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 1/4,
                0, 1/8, 0, 1/8,
                0, 0, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 1/4,
                0, 1/8, 0, 1/8,
                0, 0, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 1/2,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4, 1/4*r^2, -1/4*r^2 + 1/4*r,
                -1/4*r^2 + 1/4*r, 1/4*r^2, 1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r,
                1/4*r^2, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, 1/8*r, 1/8*r, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r^2, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4,
                -1/4*r^2 + 1/4*r, 1/4*r^2, 1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4, 1/4*r^2, -1/4*r^2 + 1/4*r,
                1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8*r, 1/8*r, -1/4*r + 1/4,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, 1/8*r, 1/8*r, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8*r, 1/8*r, -1/4*r + 1/4,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4, 1/4*r^2, -1/4*r^2 + 1/4*r,
                -1/4*r^2 + 1/4*r, 1/4*r^2, 1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r,
                1/4*r^2, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, 1/8*r, 1/8*r, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r^2, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4,
                -1/4*r^2 + 1/4*r, 1/4*r^2, 1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4, 1/4*r^2, -1/4*r^2 + 1/4*r,
                1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8*r, 1/8*r, -1/4*r + 1/4,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8*r, 1/8*r, -1/4*r + 1/4,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, 1/8*r, 1/8*r, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                1/2, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 0, 0,
                1/8, 0, 1/8, 0,
                1/4, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 0, 0,
                1/8, 0, 1/8, 0,
                1/4, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/4, 0, 0,
                0, 0, 1/4, 0,
                0, 1/4, 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                -1/4*r + 1/4, 0, 1/4*r, 0,
                -1/4*r + 1/4, 1/4*r, 0, 0,
                1/2*r, -1/4*r + 1/4, -1/4*r + 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                1/4*r, 1/8, 1/8, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                1/4*r, 1/8, 1/8, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, -1/4*r + 1/4, 0, 1/4*r,
                0, 0, -1/4*r + 1/4, 1/4*r,
                0, 1/4*r, 1/4*r, -1/2*r + 1/2
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4*r, 0, -1/4*r + 1/4, 0,
                1/4*r, -1/4*r + 1/4, 0, 0,
                -1/2*r + 1/2, 1/4*r, 1/4*r, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/4*r, 0, -1/4*r + 1/4,
                0, 0, 1/4*r, -1/4*r + 1/4,
                0, -1/4*r + 1/4, -1/4*r + 1/4, 1/2*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/4, 0,
                0, 1/4, 0, 0,
                0, 1/4, 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/8, 1/8,
                0, 1/8, 0, 1/8,
                0, 1/8, 1/8, 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/8, 1/8,
                0, 1/8, 0, 1/8,
                0, 1/8, 1/8, 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 1/2
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                1/2, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4, 1/8, 1/8, 0,
                1/8, 0, 1/8, 0,
                1/8, 1/8, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4, 1/8, 1/8, 0,
                1/8, 0, 1/8, 0,
                1/8, 1/8, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4, 1/4, 0,
                0, 0, 1/4, 0,
                0, 1/4, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/2*r, -1/4*r + 1/4, -1/4*r + 1/4, 0,
                -1/4*r + 1/4, 1/4*r, 0, 0,
                -1/4*r + 1/4, 0, 1/4*r, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, 1/8, 1/8, -1/4*r + 1/4,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, 1/8, 1/8, -1/4*r + 1/4,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4*r, 1/4*r, -1/2*r + 1/2,
                0, 0, -1/4*r + 1/4, 1/4*r,
                0, -1/4*r + 1/4, 0, 1/4*r,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/2*r + 1/2, 1/4*r, 1/4*r, 0,
                1/4*r, -1/4*r + 1/4, 0, 0,
                1/4*r, 0, -1/4*r + 1/4, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, -1/4*r + 1/4, -1/4*r + 1/4, 1/2*r,
                0, 0, 1/4*r, -1/4*r + 1/4,
                0, 1/4*r, 0, -1/4*r + 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/4, 1/4, 0,
                0, 1/4, 0, 0,
                0, 0, 1/4, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 1/4,
                0, 1/8, 0, 1/8,
                0, 0, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 1/4,
                0, 1/8, 0, 1/8,
                0, 0, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 1/2,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r^2, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4,
                -1/4*r^2 + 1/4*r, 1/4*r^2, 1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4, 1/4*r^2, -1/4*r^2 + 1/4*r,
                1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8*r, 1/8*r, -1/4*r + 1/4,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4, 1/4*r^2, -1/4*r^2 + 1/4*r,
                -1/4*r^2 + 1/4*r, 1/4*r^2, 1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r,
                1/4*r^2, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, 1/8*r, 1/8*r, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, 1/8*r, 1/8*r, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8*r, 1/8*r, -1/4*r + 1/4,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r^2, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4,
                -1/4*r^2 + 1/4*r, 1/4*r^2, 1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4, 1/4*r^2, -1/4*r^2 + 1/4*r,
                1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8*r, 1/8*r, -1/4*r + 1/4,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r + 1/4, 1/8*r, 1/8*r, 0,
                1/8, -1/8*r + 1/8, 1/8*r, 0,
                1/8, 1/8*r, -1/8*r + 1/8, 0,
                1/4*r, -1/8*r + 1/8, -1/8*r + 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/4*r + 1/8, 1/4*r^2 - 1/4*r + 1/8, -1/4*r^2 + 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2,
                -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4, 1/4*r^2, -1/4*r^2 + 1/4*r,
                -1/4*r^2 + 1/4*r, 1/4*r^2, 1/4*r^2 - 1/2*r + 1/4, -1/4*r^2 + 1/4*r,
                1/4*r^2, -1/4*r^2 + 1/4*r, -1/4*r^2 + 1/4*r, 1/4*r^2 - 1/2*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, 1/8*r, 1/8*r, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0,
                0, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 1/8*r, 1/8*r, -1/4*r + 1/4,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, -1/8*r + 1/8, -1/8*r + 1/8, 1/4*r,
                0, -1/8*r + 1/8, 1/8*r, 1/8,
                0, 1/8*r, -1/8*r + 1/8, 1/8,
                0, 1/8*r, 1/8*r, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                1/2, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 0, 0,
                1/8, 0, 1/8, 0,
                1/4, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 0, 0,
                1/8, 0, 1/8, 0,
                1/4, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/4, 0, 0,
                0, 0, 1/4, 0,
                0, 1/4, 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4*r, 0, -1/4*r + 1/4, 0,
                1/4*r, -1/4*r + 1/4, 0, 0,
                -1/2*r + 1/2, 1/4*r, 1/4*r, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/4*r, 0, -1/4*r + 1/4,
                0, 0, 1/4*r, -1/4*r + 1/4,
                0, -1/4*r + 1/4, -1/4*r + 1/4, 1/2*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                -1/4*r + 1/4, 0, 1/4*r, 0,
                -1/4*r + 1/4, 1/4*r, 0, 0,
                1/2*r, -1/4*r + 1/4, -1/4*r + 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                1/4*r, 1/8, 1/8, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                1/4*r, 1/8, 1/8, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, -1/4*r + 1/4, 0, 1/4*r,
                0, 0, -1/4*r + 1/4, 1/4*r,
                0, 1/4*r, 1/4*r, -1/2*r + 1/2
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/4, 0,
                0, 1/4, 0, 0,
                0, 1/4, 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/8, 1/8,
                0, 1/8, 0, 1/8,
                0, 1/8, 1/8, 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/8, 1/8,
                0, 1/8, 0, 1/8,
                0, 1/8, 1/8, 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 1/2
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/2, 0, 0, 0,
                1/2, 0, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4, 0, 1/4, 0,
                1/4, 1/4, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4, 0, 1/4, 0,
                1/4, 1/4, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/2, 0,
                0, 1/2, 0, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4, 1/4, 0, 0,
                1/4, 0, 1/4, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 1/8, 1/8,
                1/8, 1/8, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 1/8, 1/8,
                1/8, 1/8, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/4, 1/4,
                0, 1/4, 0, 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4, 1/4, 0, 0,
                1/4, 0, 1/4, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 1/8, 1/8,
                1/8, 1/8, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 1/8, 1/8,
                1/8, 1/8, 1/8, 1/8,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/4, 1/4,
                0, 1/4, 0, 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/2, 0, 0,
                0, 0, 1/2, 0,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/4, 0, 1/4,
                0, 0, 1/4, 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/4, 0, 1/4,
                0, 0, 1/4, 1/4,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 1/2,
                0, 0, 0, 1/2,
                0, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                1/2, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                -1/4*r + 1/4, 0, 1/4*r, 0,
                -1/4*r + 1/4, 1/4*r, 0, 0,
                1/2*r, -1/4*r + 1/4, -1/4*r + 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4*r, 0, -1/4*r + 1/4, 0,
                1/4*r, -1/4*r + 1/4, 0, 0,
                -1/2*r + 1/2, 1/4*r, 1/4*r, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/4, 0,
                0, 1/4, 0, 0,
                0, 1/4, 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 0, 0,
                1/8, 0, 1/8, 0,
                1/4, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                1/4*r, 1/8, 1/8, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/8, 1/8,
                0, 1/8, 0, 1/8,
                0, 1/8, 1/8, 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 0, 0,
                1/8, 0, 1/8, 0,
                1/4, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                1/4*r, 1/8, 1/8, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/8, 1/8,
                0, 1/8, 0, 1/8,
                0, 1/8, 1/8, 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/4, 0, 0,
                0, 0, 1/4, 0,
                0, 1/4, 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, -1/4*r + 1/4, 0, 1/4*r,
                0, 0, -1/4*r + 1/4, 1/4*r,
                0, 1/4*r, 1/4*r, -1/2*r + 1/2
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/4*r, 0, -1/4*r + 1/4,
                0, 0, 1/4*r, -1/4*r + 1/4,
                0, -1/4*r + 1/4, -1/4*r + 1/4, 1/2*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 1/2
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4, 0, 0, 0,
                1/4, 0, 0, 0,
                1/2, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/4*r, 0, -1/4*r + 1/4, 0,
                1/4*r, -1/4*r + 1/4, 0, 0,
                -1/2*r + 1/2, 1/4*r, 1/4*r, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                -1/4*r + 1/4, 0, 1/4*r, 0,
                -1/4*r + 1/4, 1/4*r, 0, 0,
                1/2*r, -1/4*r + 1/4, -1/4*r + 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/4, 0,
                0, 1/4, 0, 0,
                0, 1/4, 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 0, 0,
                1/8, 0, 1/8, 0,
                1/4, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                1/4*r, 1/8, 1/8, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/8, 1/8,
                0, 1/8, 0, 1/8,
                0, 1/8, 1/8, 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8, 1/8, 0, 0,
                1/8, 0, 1/8, 0,
                1/4, 1/8, 1/8, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                1/8*r, 1/8*r, -1/8*r + 1/8, -1/8*r + 1/8,
                1/8*r, -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8,
                -1/4*r + 1/4, 1/8, 1/8, 1/4*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                -1/8*r + 1/8, -1/8*r + 1/8, 1/8*r, 1/8*r,
                -1/8*r + 1/8, 1/8*r, -1/8*r + 1/8, 1/8*r,
                1/4*r, 1/8, 1/8, -1/4*r + 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 1/8, 1/8,
                0, 1/8, 0, 1/8,
                0, 1/8, 1/8, 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/4, 0, 0,
                0, 0, 1/4, 0,
                0, 1/4, 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 1/4*r, 0, -1/4*r + 1/4,
                0, 0, 1/4*r, -1/4*r + 1/4,
                0, -1/4*r + 1/4, -1/4*r + 1/4, 1/2*r
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, -1/4*r + 1/4, 0, 1/4*r,
                0, 0, -1/4*r + 1/4, 1/4*r,
                0, 1/4*r, 1/4*r, -1/2*r + 1/2
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 1/4,
                0, 0, 0, 1/4,
                0, 0, 0, 1/2
            ), nrow=4, ncol=4, byrow=T)
        }
    ),

    list(
        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                1, 0, 0, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                1/2, 1/4, 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                1/2, 1/4, 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 1/2, 1/2, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                1/2, 1/4, 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                1/4, 1/4, 1/4, 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                1/4, 1/4, 1/4, 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 1/4, 1/4, 1/2
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                1/2, 1/4, 1/4, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                1/4, 1/4, 1/4, 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                1/4, 1/4, 1/4, 1/4
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 1/4, 1/4, 1/2
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 1/2, 1/2, 0
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 1/4, 1/4, 1/2
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 1/4, 1/4, 1/2
            ), nrow=4, ncol=4, byrow=T)
        },

        function(r) {
            matrix(c(
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 0,
                0, 0, 0, 1
            ), nrow=4, ncol=4, byrow=T)
        }
    )
)
