## Copyright 2017 Jason Vander Woude and Nathan Ryder
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.


## This file is auto-generated by multi-model-symbolics.sage for F2
## generation plants. To generate a similar file for any generation of
## recombinant inbred line (RIL) plants, load this SAGE file in a SAGE
## interpreter and run the function 'parse_all_model_probs_to_R' with the single
## parameter being the generation of the plants where a value of 2 corresponds
## to F2, 3 corresponds to F3, etc. Running the function will print the required
## text for the R file to the console where it must be copied and pasted into a
## file called 'F{generation}.R' and saved in the appropriate directory.

## To download SAGE, visit https://www.sagemath.org/download.html


## This function will return a list of transition matrices with one list entry
## for each of the 4^(generation - 1) recomination models.

get.all.model.trans.F2 <- function() {

    list(
        function (r) {
            matrix(c(
                1, 0, 0, 0,
                0, 1, 0, 0,
                0, 0, 1, 0,
                0, 0, 0, 1
            ), nrow=4, ncol=4, byrow=T)},

        function (r) {
            matrix(c(
                -r + 1, 0, r, 0,
                0, -r + 1, 0, r,
                r, 0, -r + 1, 0,
                0, r, 0, -r + 1
            ), nrow=4, ncol=4, byrow=T)},

        function (r) {
            matrix(c(
                -r + 1, r, 0, 0,
                r, -r + 1, 0, 0,
                0, 0, -r + 1, r,
                0, 0, r, -r + 1
            ), nrow=4, ncol=4, byrow=T)},

        function (r) {
            matrix(c(
                r^2 - 2*r + 1, -r^2 + r, -r^2 + r, r^2,
                -r^2 + r, r^2 - 2*r + 1, r^2, -r^2 + r,
                -r^2 + r, r^2, r^2 - 2*r + 1, -r^2 + r,
                r^2, -r^2 + r, -r^2 + r, r^2 - 2*r + 1
            ), nrow=4, ncol=4, byrow=T)}

    )
}
