## Copyright 2017 Jason Vander Woude and Nathan Ryder
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.


## This file is auto-generated by multi-model-symbolics.sage for F5
## generation plants. To generate a similar file for any generation of
## recombinant inbred line (RIL) plants, load this SAGE file in a SAGE
## interpreter and run the function 'parse_probs_to_R' with the single
## parameter being the generation of the plants where a value of 2 corresponds
## to F2, 3 corresponds to F3, etc. Running the function will print the required
## text for the R file to the console where it must be copied and pasted into a
## file called 'F{generation}.R' and saved in the appropriate directory.

## To download SAGE, visit https://www.sagemath.org/download.html


## There is a seperate function for each file because at runtime, only one
## function will be needed, so there is no need to source to code for all other
## generations

get.trans <- function(r) {
    matrix(c(
        8/15*r^8 - 32/15*r^7 + 64/15*r^6 - 16/3*r^5 + 76/15*r^4 - 64/15*r^3 + 16/5*r^2 - 2*r + 1, -8/15*r^8 + 32/15*r^7 - 64/15*r^6 + 16/3*r^5 - 68/15*r^4 + 8/3*r^3 - 16/15*r^2 + 4/15*r, -8/15*r^8 + 32/15*r^7 - 64/15*r^6 + 16/3*r^5 - 68/15*r^4 + 8/3*r^3 - 16/15*r^2 + 4/15*r, 8/15*r^8 - 32/15*r^7 + 64/15*r^6 - 16/3*r^5 + 4*r^4 - 16/15*r^3 - 16/15*r^2 + 22/15*r,
        -8*r^8 + 32*r^7 - 64*r^6 + 80*r^5 - 68*r^4 + 40*r^3 - 16*r^2 + 4*r, 8*r^8 - 32*r^7 + 64*r^6 - 80*r^5 + 76*r^4 - 56*r^3 + 28*r^2 - 8*r + 1, 8*r^8 - 32*r^7 + 64*r^6 - 80*r^5 + 60*r^4 - 24*r^3 + 4*r^2, -8*r^8 + 32*r^7 - 64*r^6 + 80*r^5 - 68*r^4 + 40*r^3 - 16*r^2 + 4*r,
        -8*r^8 + 32*r^7 - 64*r^6 + 80*r^5 - 68*r^4 + 40*r^3 - 16*r^2 + 4*r, 8*r^8 - 32*r^7 + 64*r^6 - 80*r^5 + 60*r^4 - 24*r^3 + 4*r^2, 8*r^8 - 32*r^7 + 64*r^6 - 80*r^5 + 76*r^4 - 56*r^3 + 28*r^2 - 8*r + 1, -8*r^8 + 32*r^7 - 64*r^6 + 80*r^5 - 68*r^4 + 40*r^3 - 16*r^2 + 4*r,
        8/15*r^8 - 32/15*r^7 + 64/15*r^6 - 16/3*r^5 + 4*r^4 - 16/15*r^3 - 16/15*r^2 + 22/15*r, -8/15*r^8 + 32/15*r^7 - 64/15*r^6 + 16/3*r^5 - 68/15*r^4 + 8/3*r^3 - 16/15*r^2 + 4/15*r, -8/15*r^8 + 32/15*r^7 - 64/15*r^6 + 16/3*r^5 - 68/15*r^4 + 8/3*r^3 - 16/15*r^2 + 4/15*r, 8/15*r^8 - 32/15*r^7 + 64/15*r^6 - 16/3*r^5 + 76/15*r^4 - 64/15*r^3 + 16/5*r^2 - 2*r + 1
    ), nrow=4, ncol=4, byrow=T)
}

get.site.pair.trans <- function(r) {
    matrix(c(
        1/4*r^8 - r^7 + 2*r^6 - 5/2*r^5 + 19/8*r^4 - 2*r^3 + 3/2*r^2 - 15/16*r + 15/32, -1/4*r^8 + r^7 - 2*r^6 + 5/2*r^5 - 17/8*r^4 + 5/4*r^3 - 1/2*r^2 + 1/8*r, -1/4*r^8 + r^7 - 2*r^6 + 5/2*r^5 - 17/8*r^4 + 5/4*r^3 - 1/2*r^2 + 1/8*r, 1/4*r^8 - r^7 + 2*r^6 - 5/2*r^5 + 15/8*r^4 - 1/2*r^3 - 1/2*r^2 + 11/16*r,
        -1/4*r^8 + r^7 - 2*r^6 + 5/2*r^5 - 17/8*r^4 + 5/4*r^3 - 1/2*r^2 + 1/8*r, 1/4*r^8 - r^7 + 2*r^6 - 5/2*r^5 + 19/8*r^4 - 7/4*r^3 + 7/8*r^2 - 1/4*r + 1/32, 1/4*r^8 - r^7 + 2*r^6 - 5/2*r^5 + 15/8*r^4 - 3/4*r^3 + 1/8*r^2, -1/4*r^8 + r^7 - 2*r^6 + 5/2*r^5 - 17/8*r^4 + 5/4*r^3 - 1/2*r^2 + 1/8*r,
        -1/4*r^8 + r^7 - 2*r^6 + 5/2*r^5 - 17/8*r^4 + 5/4*r^3 - 1/2*r^2 + 1/8*r, 1/4*r^8 - r^7 + 2*r^6 - 5/2*r^5 + 15/8*r^4 - 3/4*r^3 + 1/8*r^2, 1/4*r^8 - r^7 + 2*r^6 - 5/2*r^5 + 19/8*r^4 - 7/4*r^3 + 7/8*r^2 - 1/4*r + 1/32, -1/4*r^8 + r^7 - 2*r^6 + 5/2*r^5 - 17/8*r^4 + 5/4*r^3 - 1/2*r^2 + 1/8*r,
        1/4*r^8 - r^7 + 2*r^6 - 5/2*r^5 + 15/8*r^4 - 1/2*r^3 - 1/2*r^2 + 11/16*r, -1/4*r^8 + r^7 - 2*r^6 + 5/2*r^5 - 17/8*r^4 + 5/4*r^3 - 1/2*r^2 + 1/8*r, -1/4*r^8 + r^7 - 2*r^6 + 5/2*r^5 - 17/8*r^4 + 5/4*r^3 - 1/2*r^2 + 1/8*r, 1/4*r^8 - r^7 + 2*r^6 - 5/2*r^5 + 19/8*r^4 - 2*r^3 + 3/2*r^2 - 15/16*r + 15/32
    ), nrow=4, ncol=4, byrow=T)
}
