## Copyright 2017 Jason Vander Woude and Nathan Ryder
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.


## This file is auto-generated by multi-model-symbolics.sage for F6
## generation plants. To generate a similar file for any generation of
## recombinant inbred line (RIL) plants, load this SAGE file in a SAGE
## interpreter and run the function 'parse_probs_to_R' with the single
## parameter being the generation of the plants where a value of 2 corresponds
## to F2, 3 corresponds to F3, etc. Running the function will print the required
## text for the R file to the console where it must be copied and pasted into a
## file called 'F{generation}.R' and saved in the appropriate directory.

## To download SAGE, visit https://www.sagemath.org/download.html


## There is a seperate function for each file because at runtime, only one
## function will be needed, so there is no need to source to code for all other
## generations

get.trans <- function(r) {
    matrix(c(
        16/31*r^10 - 80/31*r^9 + 200/31*r^8 - 320/31*r^7 + 360/31*r^6 - 312/31*r^5 + 236/31*r^4 - 168/31*r^3 + 109/31*r^2 - 2*r + 1, -16/31*r^10 + 80/31*r^9 - 200/31*r^8 + 320/31*r^7 - 360/31*r^6 + 296/31*r^5 - 180/31*r^4 + 80/31*r^3 - 25/31*r^2 + 5/31*r, -16/31*r^10 + 80/31*r^9 - 200/31*r^8 + 320/31*r^7 - 360/31*r^6 + 296/31*r^5 - 180/31*r^4 + 80/31*r^3 - 25/31*r^2 + 5/31*r, 16/31*r^10 - 80/31*r^9 + 200/31*r^8 - 320/31*r^7 + 360/31*r^6 - 280/31*r^5 + 4*r^4 + 8/31*r^3 - 59/31*r^2 + 52/31*r,
        -16*r^10 + 80*r^9 - 200*r^8 + 320*r^7 - 360*r^6 + 296*r^5 - 180*r^4 + 80*r^3 - 25*r^2 + 5*r, 16*r^10 - 80*r^9 + 200*r^8 - 320*r^7 + 360*r^6 - 312*r^5 + 220*r^4 - 120*r^3 + 45*r^2 - 10*r + 1, 16*r^10 - 80*r^9 + 200*r^8 - 320*r^7 + 360*r^6 - 280*r^5 + 140*r^4 - 40*r^3 + 5*r^2, -16*r^10 + 80*r^9 - 200*r^8 + 320*r^7 - 360*r^6 + 296*r^5 - 180*r^4 + 80*r^3 - 25*r^2 + 5*r,
        -16*r^10 + 80*r^9 - 200*r^8 + 320*r^7 - 360*r^6 + 296*r^5 - 180*r^4 + 80*r^3 - 25*r^2 + 5*r, 16*r^10 - 80*r^9 + 200*r^8 - 320*r^7 + 360*r^6 - 280*r^5 + 140*r^4 - 40*r^3 + 5*r^2, 16*r^10 - 80*r^9 + 200*r^8 - 320*r^7 + 360*r^6 - 312*r^5 + 220*r^4 - 120*r^3 + 45*r^2 - 10*r + 1, -16*r^10 + 80*r^9 - 200*r^8 + 320*r^7 - 360*r^6 + 296*r^5 - 180*r^4 + 80*r^3 - 25*r^2 + 5*r,
        16/31*r^10 - 80/31*r^9 + 200/31*r^8 - 320/31*r^7 + 360/31*r^6 - 280/31*r^5 + 4*r^4 + 8/31*r^3 - 59/31*r^2 + 52/31*r, -16/31*r^10 + 80/31*r^9 - 200/31*r^8 + 320/31*r^7 - 360/31*r^6 + 296/31*r^5 - 180/31*r^4 + 80/31*r^3 - 25/31*r^2 + 5/31*r, -16/31*r^10 + 80/31*r^9 - 200/31*r^8 + 320/31*r^7 - 360/31*r^6 + 296/31*r^5 - 180/31*r^4 + 80/31*r^3 - 25/31*r^2 + 5/31*r, 16/31*r^10 - 80/31*r^9 + 200/31*r^8 - 320/31*r^7 + 360/31*r^6 - 312/31*r^5 + 236/31*r^4 - 168/31*r^3 + 109/31*r^2 - 2*r + 1
    ), nrow=4, ncol=4, byrow=T)
}

get.gen.trans <- function(r) {
    c(
        AA = 1/2*r^10 - 5/2*r^9 + 25/4*r^8 - 10*r^7 + 45/4*r^6 - 39/4*r^5 + 59/8*r^4 - 21/4*r^3 + 109/32*r^2 - 31/16*r + 31/32,
        HH = r^10 - 5*r^9 + 25/2*r^8 - 20*r^7 + 45/2*r^6 - 37/2*r^5 + 45/4*r^4 - 5*r^3 + 25/16*r^2 - 5/16*r + 1/32,
        AH = -2*r^10 + 10*r^9 - 25*r^8 + 40*r^7 - 45*r^6 + 37*r^5 - 45/2*r^4 + 10*r^3 - 25/8*r^2 + 5/8*r,
        AB = 1/2*r^10 - 5/2*r^9 + 25/4*r^8 - 10*r^7 + 45/4*r^6 - 35/4*r^5 + 31/8*r^4 + 1/4*r^3 - 59/32*r^2 + 13/8*r
    )
}
